### ISSUE TITLE
Malformed link at yoast.com

### ISSUE THREAD

**Issue by hearvox** [Yoast/fact-check#35]
Thanks for this plug, testing now. Found a bad link on your page:
https://yoast.com/new-plugin-add-on-fact-check-for-yoast-seo-1-4/

Your link to this Issues page is a 404 b/c URL (on link-text "here") has a trailing ".":
https://github.com/Yoast/fact-check/issues.

Should be:
https://github.com/Yoast/fact-check/issues

Also, gotta mention, linking on just "here" is bad a11y:
https://www.w3.org/QA/Tips/noClickHere.html

**Comment by terw-dan** [comment]
Thanks for your issue. 
I've fixed the link on the page. Regarding the bad a11y, I'll let our editors look at that when they are back in the office.

**Comment by Doni1985** [comment]
And the link behind "here" is still including the full-stop at the end (notwithstanding the "here"-issue, 404 issue is still irritating) 

Question: Does it make sense to test the addon on a German language homepage?

**Comment by terw-dan** [comment]
Currently we only support English and Dutch. We would like to include German, and many other languages.
